# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project 2/project 2.srcs/sources_1/bd/design_1/ip/design_1_my_axi_slave_0_0/design_1_my_axi_slave_0_0.xci
# IP: The module: 'design_1_my_axi_slave_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project 2/project 2.gen/sources_1/bd/design_1/ip/design_1_my_axi_slave_0_0/ip/blk_true_dual_port_mem_gen_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_true_dual_port_mem_gen_2 || ORIG_REF_NAME==blk_true_dual_port_mem_gen_2} -quiet] -quiet

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project 2/project 2.gen/sources_1/bd/design_1/ip/design_1_my_axi_slave_0_0/ip/blk_true_dual_port_mem_gen_2_ooc.xdc

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project 2/project 2.srcs/sources_1/bd/design_1/ip/design_1_my_axi_slave_0_0/design_1_my_axi_slave_0_0.xci
# IP: The module: 'design_1_my_axi_slave_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project 2/project 2.gen/sources_1/bd/design_1/ip/design_1_my_axi_slave_0_0/ip/blk_true_dual_port_mem_gen_2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_true_dual_port_mem_gen_2 || ORIG_REF_NAME==blk_true_dual_port_mem_gen_2} -quiet] -quiet

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project 2/project 2.gen/sources_1/bd/design_1/ip/design_1_my_axi_slave_0_0/ip/blk_true_dual_port_mem_gen_2_ooc.xdc
