# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/bd_minimal/bd_minimal.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_minimal || ORIG_REF_NAME==bd_minimal} -quiet] -quiet

# IP: bd/bd_minimal/ip/bd_minimal_zynq_ultra_ps_e_0_0/bd_minimal_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_minimal_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==bd_minimal_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/bd_minimal/ip/bd_minimal_proc_sys_reset_0_0/bd_minimal_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_minimal_proc_sys_reset_0_0 || ORIG_REF_NAME==bd_minimal_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_minimal_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_minimal_smartconnect_0_0 || ORIG_REF_NAME==bd_minimal_smartconnect_0_0} -quiet] -quiet

# IP: bd/bd_minimal/ip/bd_minimal_util_vector_logic_0_0/bd_minimal_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_minimal_util_vector_logic_0_0 || ORIG_REF_NAME==bd_minimal_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/bd_minimal/ip/bd_minimal_my_axi_slave_0_0/bd_minimal_my_axi_slave_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_minimal_my_axi_slave_0_0 || ORIG_REF_NAME==bd_minimal_my_axi_slave_0_0} -quiet] -quiet

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/bd_minimal_ooc.xdc
