# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.srcs/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_minimal_smartconnect_0_0.xci
# IP: The module: 'bd_minimal_smartconnect_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/bd_fc8c.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_0/bd_fc8c_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_1/bd_fc8c_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_2/bd_fc8c_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_3/bd_fc8c_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_4/bd_fc8c_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_5/bd_fc8c_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_6/bd_fc8c_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_7/bd_fc8c_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_8/bd_fc8c_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_9/bd_fc8c_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_10/bd_fc8c_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_11/bd_fc8c_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_12/bd_fc8c_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_13/bd_fc8c_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_14/bd_fc8c_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_15/bd_fc8c_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_16/bd_fc8c_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_17/bd_fc8c_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_18/bd_fc8c_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_19/bd_fc8c_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_20/bd_fc8c_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_21/bd_fc8c_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_22/bd_fc8c_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_23/bd_fc8c_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_24/bd_fc8c_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_25/bd_fc8c_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_26/bd_fc8c_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_27/bd_fc8c_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_28/bd_fc8c_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_29/bd_fc8c_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_30/bd_fc8c_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_31/bd_fc8c_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_32/bd_fc8c_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_1/bd_fc8c_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_1/bd_fc8c_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_2/bd_fc8c_arinsw_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_3/bd_fc8c_rinsw_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_4/bd_fc8c_awinsw_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_5/bd_fc8c_winsw_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_6/bd_fc8c_binsw_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_7/bd_fc8c_aroutsw_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_8/bd_fc8c_routsw_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_9/bd_fc8c_awoutsw_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_10/bd_fc8c_woutsw_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_11/bd_fc8c_boutsw_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_12/bd_fc8c_arni_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_13/bd_fc8c_rni_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_14/bd_fc8c_awni_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_15/bd_fc8c_wni_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_16/bd_fc8c_bni_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_20/bd_fc8c_s00a2s_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_21/bd_fc8c_sarn_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_22/bd_fc8c_srn_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_23/bd_fc8c_sawn_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_24/bd_fc8c_swn_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_25/bd_fc8c_sbn_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_26/bd_fc8c_m00s2a_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_27/bd_fc8c_m00arn_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_28/bd_fc8c_m00rn_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_29/bd_fc8c_m00awn_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_30/bd_fc8c_m00wn_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_31/bd_fc8c_m00bn_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_minimal_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.srcs/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_minimal_smartconnect_0_0.xci
# IP: The module: 'bd_minimal_smartconnect_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/bd_fc8c.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_0/bd_fc8c_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_1/bd_fc8c_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_2/bd_fc8c_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_3/bd_fc8c_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_4/bd_fc8c_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_5/bd_fc8c_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_6/bd_fc8c_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_7/bd_fc8c_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_8/bd_fc8c_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_9/bd_fc8c_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_10/bd_fc8c_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_11/bd_fc8c_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_12/bd_fc8c_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_13/bd_fc8c_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_14/bd_fc8c_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_15/bd_fc8c_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_16/bd_fc8c_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_17/bd_fc8c_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_18/bd_fc8c_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_19/bd_fc8c_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_20/bd_fc8c_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_21/bd_fc8c_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_22/bd_fc8c_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_23/bd_fc8c_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_24/bd_fc8c_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_25/bd_fc8c_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_26/bd_fc8c_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_27/bd_fc8c_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_28/bd_fc8c_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_29/bd_fc8c_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_30/bd_fc8c_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_31/bd_fc8c_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_32/bd_fc8c_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_1/bd_fc8c_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_1/bd_fc8c_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_2/bd_fc8c_arinsw_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_3/bd_fc8c_rinsw_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_4/bd_fc8c_awinsw_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_5/bd_fc8c_winsw_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_6/bd_fc8c_binsw_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_7/bd_fc8c_aroutsw_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_8/bd_fc8c_routsw_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_9/bd_fc8c_awoutsw_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_10/bd_fc8c_woutsw_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_11/bd_fc8c_boutsw_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_12/bd_fc8c_arni_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_13/bd_fc8c_rni_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_14/bd_fc8c_awni_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_15/bd_fc8c_wni_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_16/bd_fc8c_bni_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_20/bd_fc8c_s00a2s_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_21/bd_fc8c_sarn_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_22/bd_fc8c_srn_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_23/bd_fc8c_sawn_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_24/bd_fc8c_swn_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_25/bd_fc8c_sbn_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_26/bd_fc8c_m00s2a_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_27/bd_fc8c_m00arn_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_28/bd_fc8c_m00rn_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_29/bd_fc8c_m00awn_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_30/bd_fc8c_m00wn_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_31/bd_fc8c_m00bn_0_ooc.xdc

# XDC: c:/Users/Randy/Desktop/repos/FPGA-Ray_2/project_1/project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_minimal_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
