#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : bd_minimal.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Sat Mar 21 16:08:54 -0700 2026
# SW Build 3671981 on Fri Oct 14 05:00:03 MDT 2022
#
# Tool Version Limit: 2022.10 
#
# usage: bd_minimal.sh [-help]
# usage: bd_minimal.sh [-lib_map_path]
# usage: bd_minimal.sh [-noclean_files]
# usage: bd_minimal.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'bd_minimal.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Set vlogan compile options
vlogan_opts="-full64 "

# Set vhdlan compile options
vhdlan_opts="-full64 "

# Set vcs elaboration options
vcs_elab_opts="-full64 -debug_acc+pp+dmptf -t ps -licqueue -l elaborate.log "

# Set vcs simulation options
vcs_sim_opts="-ucli -licqueue -l simulate.log "

# Design libraries
design_libs=(xilinx_vip xpm axi_infrastructure_v1_1_0 axi_vip_v1_1_13 zynq_ultra_ps_e_vip_v1_0_13 xil_defaultlib lib_cdc_v1_0_2 proc_sys_reset_v5_0_13 xlconstant_v1_1_7 smartconnect_v1_0 axi_register_slice_v2_1_27 util_vector_logic_v2_0_2 blk_mem_gen_v8_4_5)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "bd_minimal.sh - Script generated by export_simulation (Vivado v2022.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "C:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "C:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "C:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "C:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "C:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "C:/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
    "C:/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "C:/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_13 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/ffc2/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work zynq_ultra_ps_e_vip_v1_0_13 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/abef/hdl/zynq_ultra_ps_e_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/bd_minimal/ip/bd_minimal_zynq_ultra_ps_e_0_0/sim/bd_minimal_zynq_ultra_ps_e_0_0_vip_wrapper.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/bd_minimal/ip/bd_minimal_proc_sys_reset_0_0/sim/bd_minimal_proc_sys_reset_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconstant_v1_1_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/badb/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_0/sim/bd_fc8c_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_1/sim/bd_fc8c_psr_aclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv" \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/c012/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_2/sim/bd_fc8c_arinsw_0.sv" \
    "$ref_dir/../../../bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_3/sim/bd_fc8c_rinsw_0.sv" \
    "$ref_dir/../../../bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_4/sim/bd_fc8c_awinsw_0.sv" \
    "$ref_dir/../../../bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_5/sim/bd_fc8c_winsw_0.sv" \
    "$ref_dir/../../../bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_6/sim/bd_fc8c_binsw_0.sv" \
    "$ref_dir/../../../bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_7/sim/bd_fc8c_aroutsw_0.sv" \
    "$ref_dir/../../../bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_8/sim/bd_fc8c_routsw_0.sv" \
    "$ref_dir/../../../bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_9/sim/bd_fc8c_awoutsw_0.sv" \
    "$ref_dir/../../../bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_10/sim/bd_fc8c_woutsw_0.sv" \
    "$ref_dir/../../../bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_11/sim/bd_fc8c_boutsw_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/66be/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_12/sim/bd_fc8c_arni_0.sv" \
    "$ref_dir/../../../bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_13/sim/bd_fc8c_rni_0.sv" \
    "$ref_dir/../../../bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_14/sim/bd_fc8c_awni_0.sv" \
    "$ref_dir/../../../bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_15/sim/bd_fc8c_wni_0.sv" \
    "$ref_dir/../../../bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_16/sim/bd_fc8c_bni_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/be1f/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_17/sim/bd_fc8c_s00mmu_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/4fd2/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_18/sim/bd_fc8c_s00tr_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/637d/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_19/sim/bd_fc8c_s00sic_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/f38e/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_20/sim/bd_fc8c_s00a2s_0.sv" \
    "$ref_dir/../../../bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_21/sim/bd_fc8c_sarn_0.sv" \
    "$ref_dir/../../../bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_22/sim/bd_fc8c_srn_0.sv" \
    "$ref_dir/../../../bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_23/sim/bd_fc8c_sawn_0.sv" \
    "$ref_dir/../../../bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_24/sim/bd_fc8c_swn_0.sv" \
    "$ref_dir/../../../bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_25/sim/bd_fc8c_sbn_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/9cc5/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_26/sim/bd_fc8c_m00s2a_0.sv" \
    "$ref_dir/../../../bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_27/sim/bd_fc8c_m00arn_0.sv" \
    "$ref_dir/../../../bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_28/sim/bd_fc8c_m00rn_0.sv" \
    "$ref_dir/../../../bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_29/sim/bd_fc8c_m00awn_0.sv" \
    "$ref_dir/../../../bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_30/sim/bd_fc8c_m00wn_0.sv" \
    "$ref_dir/../../../bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_31/sim/bd_fc8c_m00bn_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/6bba/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/ip/ip_32/sim/bd_fc8c_m00e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/bd_0/sim/bd_fc8c.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_27 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/f0b4/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/bd_minimal/ip/bd_minimal_smartconnect_0_0/sim/bd_minimal_smartconnect_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work util_vector_logic_v2_0_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/3d84/hdl/util_vector_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/bd_minimal/ip/bd_minimal_util_vector_logic_0_0/sim/bd_minimal_util_vector_logic_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work blk_mem_gen_v8_4_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ip/bd_minimal_my_axi_slave_0_0/ip/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/bd_minimal/ip/bd_minimal_my_axi_slave_0_0/ip/sim/blk_true_dual_port_mem_gen_2.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/bd_minimal/ipshared/4ea7/hdl/mem_test_module_for_v4_0.vhd" \
    "$ref_dir/../../../bd/bd_minimal/ipshared/4ea7/hdl/proto_mem_v3_0_S00_AXI.vhd" \
    "$ref_dir/../../../bd/bd_minimal/ipshared/4ea7/hdl/proto_mem_v4_0.vhd" \
    "$ref_dir/../../../bd/bd_minimal/ip/bd_minimal_my_axi_slave_0_0/sim/bd_minimal_my_axi_slave_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/bd_minimal/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/bd_minimal/sim/bd_minimal.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log
}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.bd_minimal xil_defaultlib.glbl -o bd_minimal_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./bd_minimal_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./bd_minimal.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key bd_minimal_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc bd_minimal_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./bd_minimal.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: bd_minimal.sh [-help]\n\
Usage: bd_minimal.sh [-lib_map_path]\n\
Usage: bd_minimal.sh [-reset_run]\n\
Usage: bd_minimal.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
